# Generated by Django 2.2.4 on 2023-08-25 02:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('honor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='honor',
            options={'ordering': ('-publishDate',), 'verbose_name': '班级荣誉', 'verbose_name_plural': '班级荣誉'},
        ),
        migrations.AddField(
            model_name='honor',
            name='honorType',
            field=models.CharField(choices=[('学术荣誉', '学术荣誉'), ('艺术荣誉', '艺术荣誉'), ('体育荣誉', '体育荣誉')], default='', max_length=50, verbose_name='荣誉类型'),
        ),
        migrations.AddField(
            model_name='honor',
            name='publishDate',
            field=models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='honor',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='荣誉名称'),
        ),
        migrations.AlterField(
            model_name='honor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='honor/', verbose_name='荣誉照片'),
        ),
    ]
