# Generated by Django 2.2.4 on 2023-07-20 06:23

import DjangoUeditor.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='新闻标题')),
                ('newType', models.CharField(choices=[('班级活动', '班级活动'), ('语文', '语文'), ('数学', '数学'), ('英语', '英语'), ('物理', '物理'), ('化学', '化学'), ('生物', '生物'), ('地理', '地理'), ('历史', '历史'), ('政治', '政治')], max_length=50, verbose_name='新闻内容')),
                ('publishDate', models.DateTimeField(default=django.utils.timezone.now, max_length=20, verbose_name='发布时间')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('description', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
            ],
            options={
                'verbose_name': '班级活动',
                'verbose_name_plural': '班级活动',
                'ordering': ['-publishDate'],
            },
        ),
    ]
