# Generated by Django 2.2.4 on 2023-08-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyNew',
        ),
    ]
