# Generated by Django 2.2.4 on 2023-08-27 00:35

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_myactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='myactivity',
            name='abstract',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='简介'),
        ),
        migrations.AddField(
            model_name='myactivity',
            name='photo',
            field=models.ImageField(blank=True, upload_to='activities/', verbose_name='活动首页照片'),
        ),
    ]
