# Generated by Django 2.2.4 on 2023-08-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20230827_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myactivity',
            name='abstract',
            field=models.TextField(max_length=120, verbose_name='简介'),
        ),
    ]
