# Generated by Django 2.2.4 on 2023-08-28 00:03

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjectscenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mysubject',
            options={'ordering': ['-publishDate'], 'verbose_name': '学科新闻', 'verbose_name_plural': '学科新闻'},
        ),
        migrations.AddField(
            model_name='mysubject',
            name='abstract',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='简介'),
        ),
    ]
