# Generated by Django 2.2.4 on 2023-08-28 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectscenter', '0002_auto_20230828_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysubject',
            name='abstract',
            field=models.TextField(max_length=100, verbose_name='简介'),
        ),
    ]
