# Generated by Django 2.2.4 on 2023-08-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjectscenter', '0003_auto_20230828_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysubject',
            name='photo',
            field=models.ImageField(blank=True, upload_to='subjectscenter/images'),
        ),
    ]
