# Generated by Django 2.2.4 on 2023-08-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentssharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doc',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Doc/', verbose_name='资料图片'),
        ),
    ]
